import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

import { cp } from 'fs/promises';

const copyFunction = (files = {}) => (async () => {
  const operations = Object.entries(files)
    .map(
      ([source, target]) => cp(source, target, {
		preserveTimestamps: true,
	  })
    );
  await Promise.all(operations);
});

const copyFilePlugin = ({before, after}) => ({
  name: 'copyFile',
  async setup(build) {
    before && build.onStart(copyFunction(before));
    after && build.onEnd(copyFunction(after));
  }
});


const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

esbuild
	.build({
		banner: {
			js: banner,
		},
		entryPoints: ["src/main.ts"],
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/closebrackets",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/comment",
			"@codemirror/fold",
			"@codemirror/gutter",
			"@codemirror/highlight",
			"@codemirror/history",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/matchbrackets",
			"@codemirror/panel",
			"@codemirror/rangeset",
			"@codemirror/rectangular-selection",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/stream-parser",
			"@codemirror/text",
			"@codemirror/tooltip",
			"@codemirror/view",
			...builtins,
		],
		format: "cjs",
		watch: !prod,
		target: "es2016",
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		outfile: "main.js",
		plugins: [copyFilePlugin({
			after: { // copy after bundling
			  'main.js': '/Users/brian/Library/Mobile Documents/iCloud~md~obsidian/Documents/Life/.obsidian/plugins/obsidian-full-calendar/main.js',
			  'manifest.json': '/Users/brian/Library/Mobile Documents/iCloud~md~obsidian/Documents/Life/.obsidian/plugins/obsidian-full-calendar/manifest.json',
			  'main.css': "/Users/brian/Library/Mobile Documents/iCloud~md~obsidian/Documents/Life/.obsidian/plugins/obsidian-full-calendar/styles.css",
			}
		  })]
	})
	.catch(() => process.exit(1));
