name: docs
on:
    push:
        branches:
            - main
        paths:
            - docs/**
            - mkdocs.yml # this isn't actual docs but could affect rendering
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.x
            - run: |
                  pip install mkdocs-material
                  mkdocs gh-deploy --force
